// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameServer.proto

#ifndef PROTOBUF_INCLUDED_NameServer_2eproto
#define PROTOBUF_INCLUDED_NameServer_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_NameServer_2eproto 

namespace protobuf_NameServer_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_NameServer_2eproto
namespace NameServer {
class BlockInfo;
class BlockInfoDefaultTypeInternal;
extern BlockInfoDefaultTypeInternal _BlockInfo_default_instance_;
class BlockStore;
class BlockStoreDefaultTypeInternal;
extern BlockStoreDefaultTypeInternal _BlockStore_default_instance_;
class FileInfo;
class FileInfoDefaultTypeInternal;
extern FileInfoDefaultTypeInternal _FileInfo_default_instance_;
class ServerInfo;
class ServerInfoDefaultTypeInternal;
extern ServerInfoDefaultTypeInternal _ServerInfo_default_instance_;
}  // namespace NameServer
namespace google {
namespace protobuf {
template<> ::NameServer::BlockInfo* Arena::CreateMaybeMessage<::NameServer::BlockInfo>(Arena*);
template<> ::NameServer::BlockStore* Arena::CreateMaybeMessage<::NameServer::BlockStore>(Arena*);
template<> ::NameServer::FileInfo* Arena::CreateMaybeMessage<::NameServer::FileInfo>(Arena*);
template<> ::NameServer::ServerInfo* Arena::CreateMaybeMessage<::NameServer::ServerInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace NameServer {

// ===================================================================

class ServerInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NameServer.ServerInfo) */ {
 public:
  ServerInfo();
  virtual ~ServerInfo();

  ServerInfo(const ServerInfo& from);

  inline ServerInfo& operator=(const ServerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerInfo(ServerInfo&& from) noexcept
    : ServerInfo() {
    *this = ::std::move(from);
  }

  inline ServerInfo& operator=(ServerInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerInfo* internal_default_instance() {
    return reinterpret_cast<const ServerInfo*>(
               &_ServerInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ServerInfo* other);
  friend void swap(ServerInfo& a, ServerInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerInfo* New() const final {
    return CreateMaybeMessage<ServerInfo>(NULL);
  }

  ServerInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ServerInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ServerInfo& from);
  void MergeFrom(const ServerInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string address = 1;
  void clear_address();
  static const int kAddressFieldNumber = 1;
  const ::std::string& address() const;
  void set_address(const ::std::string& value);
  #if LANG_CXX11
  void set_address(::std::string&& value);
  #endif
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  ::std::string* mutable_address();
  ::std::string* release_address();
  void set_allocated_address(::std::string* address);

  // bytes hash = 2;
  void clear_hash();
  static const int kHashFieldNumber = 2;
  const ::std::string& hash() const;
  void set_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_hash(::std::string&& value);
  #endif
  void set_hash(const char* value);
  void set_hash(const void* value, size_t size);
  ::std::string* mutable_hash();
  ::std::string* release_hash();
  void set_allocated_hash(::std::string* hash);

  // @@protoc_insertion_point(class_scope:NameServer.ServerInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  ::google::protobuf::internal::ArenaStringPtr hash_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_NameServer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FileInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NameServer.FileInfo) */ {
 public:
  FileInfo();
  virtual ~FileInfo();

  FileInfo(const FileInfo& from);

  inline FileInfo& operator=(const FileInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FileInfo(FileInfo&& from) noexcept
    : FileInfo() {
    *this = ::std::move(from);
  }

  inline FileInfo& operator=(FileInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FileInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FileInfo* internal_default_instance() {
    return reinterpret_cast<const FileInfo*>(
               &_FileInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(FileInfo* other);
  friend void swap(FileInfo& a, FileInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FileInfo* New() const final {
    return CreateMaybeMessage<FileInfo>(NULL);
  }

  FileInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FileInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FileInfo& from);
  void MergeFrom(const FileInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string fileName = 1;
  void clear_filename();
  static const int kFileNameFieldNumber = 1;
  const ::std::string& filename() const;
  void set_filename(const ::std::string& value);
  #if LANG_CXX11
  void set_filename(::std::string&& value);
  #endif
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  ::std::string* mutable_filename();
  ::std::string* release_filename();
  void set_allocated_filename(::std::string* filename);

  // uint64 fileSize = 2;
  void clear_filesize();
  static const int kFileSizeFieldNumber = 2;
  ::google::protobuf::uint64 filesize() const;
  void set_filesize(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:NameServer.FileInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr filename_;
  ::google::protobuf::uint64 filesize_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_NameServer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BlockStore : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NameServer.BlockStore) */ {
 public:
  BlockStore();
  virtual ~BlockStore();

  BlockStore(const BlockStore& from);

  inline BlockStore& operator=(const BlockStore& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BlockStore(BlockStore&& from) noexcept
    : BlockStore() {
    *this = ::std::move(from);
  }

  inline BlockStore& operator=(BlockStore&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BlockStore& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BlockStore* internal_default_instance() {
    return reinterpret_cast<const BlockStore*>(
               &_BlockStore_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(BlockStore* other);
  friend void swap(BlockStore& a, BlockStore& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BlockStore* New() const final {
    return CreateMaybeMessage<BlockStore>(NULL);
  }

  BlockStore* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BlockStore>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BlockStore& from);
  void MergeFrom(const BlockStore& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlockStore* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string serverAddress = 1;
  void clear_serveraddress();
  static const int kServerAddressFieldNumber = 1;
  const ::std::string& serveraddress() const;
  void set_serveraddress(const ::std::string& value);
  #if LANG_CXX11
  void set_serveraddress(::std::string&& value);
  #endif
  void set_serveraddress(const char* value);
  void set_serveraddress(const char* value, size_t size);
  ::std::string* mutable_serveraddress();
  ::std::string* release_serveraddress();
  void set_allocated_serveraddress(::std::string* serveraddress);

  // bytes serverHash = 2;
  void clear_serverhash();
  static const int kServerHashFieldNumber = 2;
  const ::std::string& serverhash() const;
  void set_serverhash(const ::std::string& value);
  #if LANG_CXX11
  void set_serverhash(::std::string&& value);
  #endif
  void set_serverhash(const char* value);
  void set_serverhash(const void* value, size_t size);
  ::std::string* mutable_serverhash();
  ::std::string* release_serverhash();
  void set_allocated_serverhash(::std::string* serverhash);

  // string fileName = 3;
  void clear_filename();
  static const int kFileNameFieldNumber = 3;
  const ::std::string& filename() const;
  void set_filename(const ::std::string& value);
  #if LANG_CXX11
  void set_filename(::std::string&& value);
  #endif
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  ::std::string* mutable_filename();
  ::std::string* release_filename();
  void set_allocated_filename(::std::string* filename);

  // bytes blockHash = 6;
  void clear_blockhash();
  static const int kBlockHashFieldNumber = 6;
  const ::std::string& blockhash() const;
  void set_blockhash(const ::std::string& value);
  #if LANG_CXX11
  void set_blockhash(::std::string&& value);
  #endif
  void set_blockhash(const char* value);
  void set_blockhash(const void* value, size_t size);
  ::std::string* mutable_blockhash();
  ::std::string* release_blockhash();
  void set_allocated_blockhash(::std::string* blockhash);

  // uint64 blockIdx = 4;
  void clear_blockidx();
  static const int kBlockIdxFieldNumber = 4;
  ::google::protobuf::uint64 blockidx() const;
  void set_blockidx(::google::protobuf::uint64 value);

  // uint64 blockSize = 5;
  void clear_blocksize();
  static const int kBlockSizeFieldNumber = 5;
  ::google::protobuf::uint64 blocksize() const;
  void set_blocksize(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:NameServer.BlockStore)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr serveraddress_;
  ::google::protobuf::internal::ArenaStringPtr serverhash_;
  ::google::protobuf::internal::ArenaStringPtr filename_;
  ::google::protobuf::internal::ArenaStringPtr blockhash_;
  ::google::protobuf::uint64 blockidx_;
  ::google::protobuf::uint64 blocksize_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_NameServer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class BlockInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NameServer.BlockInfo) */ {
 public:
  BlockInfo();
  virtual ~BlockInfo();

  BlockInfo(const BlockInfo& from);

  inline BlockInfo& operator=(const BlockInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BlockInfo(BlockInfo&& from) noexcept
    : BlockInfo() {
    *this = ::std::move(from);
  }

  inline BlockInfo& operator=(BlockInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BlockInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BlockInfo* internal_default_instance() {
    return reinterpret_cast<const BlockInfo*>(
               &_BlockInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(BlockInfo* other);
  friend void swap(BlockInfo& a, BlockInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BlockInfo* New() const final {
    return CreateMaybeMessage<BlockInfo>(NULL);
  }

  BlockInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BlockInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BlockInfo& from);
  void MergeFrom(const BlockInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlockInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string fileName = 1;
  void clear_filename();
  static const int kFileNameFieldNumber = 1;
  const ::std::string& filename() const;
  void set_filename(const ::std::string& value);
  #if LANG_CXX11
  void set_filename(::std::string&& value);
  #endif
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  ::std::string* mutable_filename();
  ::std::string* release_filename();
  void set_allocated_filename(::std::string* filename);

  // bytes blockHash = 4;
  void clear_blockhash();
  static const int kBlockHashFieldNumber = 4;
  const ::std::string& blockhash() const;
  void set_blockhash(const ::std::string& value);
  #if LANG_CXX11
  void set_blockhash(::std::string&& value);
  #endif
  void set_blockhash(const char* value);
  void set_blockhash(const void* value, size_t size);
  ::std::string* mutable_blockhash();
  ::std::string* release_blockhash();
  void set_allocated_blockhash(::std::string* blockhash);

  // uint64 blockIdx = 2;
  void clear_blockidx();
  static const int kBlockIdxFieldNumber = 2;
  ::google::protobuf::uint64 blockidx() const;
  void set_blockidx(::google::protobuf::uint64 value);

  // uint64 blockSize = 3;
  void clear_blocksize();
  static const int kBlockSizeFieldNumber = 3;
  ::google::protobuf::uint64 blocksize() const;
  void set_blocksize(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:NameServer.BlockInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr filename_;
  ::google::protobuf::internal::ArenaStringPtr blockhash_;
  ::google::protobuf::uint64 blockidx_;
  ::google::protobuf::uint64 blocksize_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_NameServer_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerInfo

// string address = 1;
inline void ServerInfo::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ServerInfo::address() const {
  // @@protoc_insertion_point(field_get:NameServer.ServerInfo.address)
  return address_.GetNoArena();
}
inline void ServerInfo::set_address(const ::std::string& value) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NameServer.ServerInfo.address)
}
#if LANG_CXX11
inline void ServerInfo::set_address(::std::string&& value) {
  
  address_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NameServer.ServerInfo.address)
}
#endif
inline void ServerInfo::set_address(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NameServer.ServerInfo.address)
}
inline void ServerInfo::set_address(const char* value, size_t size) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NameServer.ServerInfo.address)
}
inline ::std::string* ServerInfo::mutable_address() {
  
  // @@protoc_insertion_point(field_mutable:NameServer.ServerInfo.address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ServerInfo::release_address() {
  // @@protoc_insertion_point(field_release:NameServer.ServerInfo.address)
  
  return address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ServerInfo::set_allocated_address(::std::string* address) {
  if (address != NULL) {
    
  } else {
    
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:NameServer.ServerInfo.address)
}

// bytes hash = 2;
inline void ServerInfo::clear_hash() {
  hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ServerInfo::hash() const {
  // @@protoc_insertion_point(field_get:NameServer.ServerInfo.hash)
  return hash_.GetNoArena();
}
inline void ServerInfo::set_hash(const ::std::string& value) {
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NameServer.ServerInfo.hash)
}
#if LANG_CXX11
inline void ServerInfo::set_hash(::std::string&& value) {
  
  hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NameServer.ServerInfo.hash)
}
#endif
inline void ServerInfo::set_hash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NameServer.ServerInfo.hash)
}
inline void ServerInfo::set_hash(const void* value, size_t size) {
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NameServer.ServerInfo.hash)
}
inline ::std::string* ServerInfo::mutable_hash() {
  
  // @@protoc_insertion_point(field_mutable:NameServer.ServerInfo.hash)
  return hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ServerInfo::release_hash() {
  // @@protoc_insertion_point(field_release:NameServer.ServerInfo.hash)
  
  return hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ServerInfo::set_allocated_hash(::std::string* hash) {
  if (hash != NULL) {
    
  } else {
    
  }
  hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hash);
  // @@protoc_insertion_point(field_set_allocated:NameServer.ServerInfo.hash)
}

// -------------------------------------------------------------------

// FileInfo

// string fileName = 1;
inline void FileInfo::clear_filename() {
  filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FileInfo::filename() const {
  // @@protoc_insertion_point(field_get:NameServer.FileInfo.fileName)
  return filename_.GetNoArena();
}
inline void FileInfo::set_filename(const ::std::string& value) {
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NameServer.FileInfo.fileName)
}
#if LANG_CXX11
inline void FileInfo::set_filename(::std::string&& value) {
  
  filename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NameServer.FileInfo.fileName)
}
#endif
inline void FileInfo::set_filename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NameServer.FileInfo.fileName)
}
inline void FileInfo::set_filename(const char* value, size_t size) {
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NameServer.FileInfo.fileName)
}
inline ::std::string* FileInfo::mutable_filename() {
  
  // @@protoc_insertion_point(field_mutable:NameServer.FileInfo.fileName)
  return filename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FileInfo::release_filename() {
  // @@protoc_insertion_point(field_release:NameServer.FileInfo.fileName)
  
  return filename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FileInfo::set_allocated_filename(::std::string* filename) {
  if (filename != NULL) {
    
  } else {
    
  }
  filename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filename);
  // @@protoc_insertion_point(field_set_allocated:NameServer.FileInfo.fileName)
}

// uint64 fileSize = 2;
inline void FileInfo::clear_filesize() {
  filesize_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 FileInfo::filesize() const {
  // @@protoc_insertion_point(field_get:NameServer.FileInfo.fileSize)
  return filesize_;
}
inline void FileInfo::set_filesize(::google::protobuf::uint64 value) {
  
  filesize_ = value;
  // @@protoc_insertion_point(field_set:NameServer.FileInfo.fileSize)
}

// -------------------------------------------------------------------

// BlockStore

// string serverAddress = 1;
inline void BlockStore::clear_serveraddress() {
  serveraddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BlockStore::serveraddress() const {
  // @@protoc_insertion_point(field_get:NameServer.BlockStore.serverAddress)
  return serveraddress_.GetNoArena();
}
inline void BlockStore::set_serveraddress(const ::std::string& value) {
  
  serveraddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NameServer.BlockStore.serverAddress)
}
#if LANG_CXX11
inline void BlockStore::set_serveraddress(::std::string&& value) {
  
  serveraddress_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NameServer.BlockStore.serverAddress)
}
#endif
inline void BlockStore::set_serveraddress(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  serveraddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NameServer.BlockStore.serverAddress)
}
inline void BlockStore::set_serveraddress(const char* value, size_t size) {
  
  serveraddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NameServer.BlockStore.serverAddress)
}
inline ::std::string* BlockStore::mutable_serveraddress() {
  
  // @@protoc_insertion_point(field_mutable:NameServer.BlockStore.serverAddress)
  return serveraddress_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BlockStore::release_serveraddress() {
  // @@protoc_insertion_point(field_release:NameServer.BlockStore.serverAddress)
  
  return serveraddress_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BlockStore::set_allocated_serveraddress(::std::string* serveraddress) {
  if (serveraddress != NULL) {
    
  } else {
    
  }
  serveraddress_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), serveraddress);
  // @@protoc_insertion_point(field_set_allocated:NameServer.BlockStore.serverAddress)
}

// bytes serverHash = 2;
inline void BlockStore::clear_serverhash() {
  serverhash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BlockStore::serverhash() const {
  // @@protoc_insertion_point(field_get:NameServer.BlockStore.serverHash)
  return serverhash_.GetNoArena();
}
inline void BlockStore::set_serverhash(const ::std::string& value) {
  
  serverhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NameServer.BlockStore.serverHash)
}
#if LANG_CXX11
inline void BlockStore::set_serverhash(::std::string&& value) {
  
  serverhash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NameServer.BlockStore.serverHash)
}
#endif
inline void BlockStore::set_serverhash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  serverhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NameServer.BlockStore.serverHash)
}
inline void BlockStore::set_serverhash(const void* value, size_t size) {
  
  serverhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NameServer.BlockStore.serverHash)
}
inline ::std::string* BlockStore::mutable_serverhash() {
  
  // @@protoc_insertion_point(field_mutable:NameServer.BlockStore.serverHash)
  return serverhash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BlockStore::release_serverhash() {
  // @@protoc_insertion_point(field_release:NameServer.BlockStore.serverHash)
  
  return serverhash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BlockStore::set_allocated_serverhash(::std::string* serverhash) {
  if (serverhash != NULL) {
    
  } else {
    
  }
  serverhash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), serverhash);
  // @@protoc_insertion_point(field_set_allocated:NameServer.BlockStore.serverHash)
}

// string fileName = 3;
inline void BlockStore::clear_filename() {
  filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BlockStore::filename() const {
  // @@protoc_insertion_point(field_get:NameServer.BlockStore.fileName)
  return filename_.GetNoArena();
}
inline void BlockStore::set_filename(const ::std::string& value) {
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NameServer.BlockStore.fileName)
}
#if LANG_CXX11
inline void BlockStore::set_filename(::std::string&& value) {
  
  filename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NameServer.BlockStore.fileName)
}
#endif
inline void BlockStore::set_filename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NameServer.BlockStore.fileName)
}
inline void BlockStore::set_filename(const char* value, size_t size) {
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NameServer.BlockStore.fileName)
}
inline ::std::string* BlockStore::mutable_filename() {
  
  // @@protoc_insertion_point(field_mutable:NameServer.BlockStore.fileName)
  return filename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BlockStore::release_filename() {
  // @@protoc_insertion_point(field_release:NameServer.BlockStore.fileName)
  
  return filename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BlockStore::set_allocated_filename(::std::string* filename) {
  if (filename != NULL) {
    
  } else {
    
  }
  filename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filename);
  // @@protoc_insertion_point(field_set_allocated:NameServer.BlockStore.fileName)
}

// uint64 blockIdx = 4;
inline void BlockStore::clear_blockidx() {
  blockidx_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BlockStore::blockidx() const {
  // @@protoc_insertion_point(field_get:NameServer.BlockStore.blockIdx)
  return blockidx_;
}
inline void BlockStore::set_blockidx(::google::protobuf::uint64 value) {
  
  blockidx_ = value;
  // @@protoc_insertion_point(field_set:NameServer.BlockStore.blockIdx)
}

// uint64 blockSize = 5;
inline void BlockStore::clear_blocksize() {
  blocksize_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BlockStore::blocksize() const {
  // @@protoc_insertion_point(field_get:NameServer.BlockStore.blockSize)
  return blocksize_;
}
inline void BlockStore::set_blocksize(::google::protobuf::uint64 value) {
  
  blocksize_ = value;
  // @@protoc_insertion_point(field_set:NameServer.BlockStore.blockSize)
}

// bytes blockHash = 6;
inline void BlockStore::clear_blockhash() {
  blockhash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BlockStore::blockhash() const {
  // @@protoc_insertion_point(field_get:NameServer.BlockStore.blockHash)
  return blockhash_.GetNoArena();
}
inline void BlockStore::set_blockhash(const ::std::string& value) {
  
  blockhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NameServer.BlockStore.blockHash)
}
#if LANG_CXX11
inline void BlockStore::set_blockhash(::std::string&& value) {
  
  blockhash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NameServer.BlockStore.blockHash)
}
#endif
inline void BlockStore::set_blockhash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  blockhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NameServer.BlockStore.blockHash)
}
inline void BlockStore::set_blockhash(const void* value, size_t size) {
  
  blockhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NameServer.BlockStore.blockHash)
}
inline ::std::string* BlockStore::mutable_blockhash() {
  
  // @@protoc_insertion_point(field_mutable:NameServer.BlockStore.blockHash)
  return blockhash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BlockStore::release_blockhash() {
  // @@protoc_insertion_point(field_release:NameServer.BlockStore.blockHash)
  
  return blockhash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BlockStore::set_allocated_blockhash(::std::string* blockhash) {
  if (blockhash != NULL) {
    
  } else {
    
  }
  blockhash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), blockhash);
  // @@protoc_insertion_point(field_set_allocated:NameServer.BlockStore.blockHash)
}

// -------------------------------------------------------------------

// BlockInfo

// string fileName = 1;
inline void BlockInfo::clear_filename() {
  filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BlockInfo::filename() const {
  // @@protoc_insertion_point(field_get:NameServer.BlockInfo.fileName)
  return filename_.GetNoArena();
}
inline void BlockInfo::set_filename(const ::std::string& value) {
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NameServer.BlockInfo.fileName)
}
#if LANG_CXX11
inline void BlockInfo::set_filename(::std::string&& value) {
  
  filename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NameServer.BlockInfo.fileName)
}
#endif
inline void BlockInfo::set_filename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NameServer.BlockInfo.fileName)
}
inline void BlockInfo::set_filename(const char* value, size_t size) {
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NameServer.BlockInfo.fileName)
}
inline ::std::string* BlockInfo::mutable_filename() {
  
  // @@protoc_insertion_point(field_mutable:NameServer.BlockInfo.fileName)
  return filename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BlockInfo::release_filename() {
  // @@protoc_insertion_point(field_release:NameServer.BlockInfo.fileName)
  
  return filename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BlockInfo::set_allocated_filename(::std::string* filename) {
  if (filename != NULL) {
    
  } else {
    
  }
  filename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filename);
  // @@protoc_insertion_point(field_set_allocated:NameServer.BlockInfo.fileName)
}

// uint64 blockIdx = 2;
inline void BlockInfo::clear_blockidx() {
  blockidx_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BlockInfo::blockidx() const {
  // @@protoc_insertion_point(field_get:NameServer.BlockInfo.blockIdx)
  return blockidx_;
}
inline void BlockInfo::set_blockidx(::google::protobuf::uint64 value) {
  
  blockidx_ = value;
  // @@protoc_insertion_point(field_set:NameServer.BlockInfo.blockIdx)
}

// uint64 blockSize = 3;
inline void BlockInfo::clear_blocksize() {
  blocksize_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BlockInfo::blocksize() const {
  // @@protoc_insertion_point(field_get:NameServer.BlockInfo.blockSize)
  return blocksize_;
}
inline void BlockInfo::set_blocksize(::google::protobuf::uint64 value) {
  
  blocksize_ = value;
  // @@protoc_insertion_point(field_set:NameServer.BlockInfo.blockSize)
}

// bytes blockHash = 4;
inline void BlockInfo::clear_blockhash() {
  blockhash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BlockInfo::blockhash() const {
  // @@protoc_insertion_point(field_get:NameServer.BlockInfo.blockHash)
  return blockhash_.GetNoArena();
}
inline void BlockInfo::set_blockhash(const ::std::string& value) {
  
  blockhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NameServer.BlockInfo.blockHash)
}
#if LANG_CXX11
inline void BlockInfo::set_blockhash(::std::string&& value) {
  
  blockhash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NameServer.BlockInfo.blockHash)
}
#endif
inline void BlockInfo::set_blockhash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  blockhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NameServer.BlockInfo.blockHash)
}
inline void BlockInfo::set_blockhash(const void* value, size_t size) {
  
  blockhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NameServer.BlockInfo.blockHash)
}
inline ::std::string* BlockInfo::mutable_blockhash() {
  
  // @@protoc_insertion_point(field_mutable:NameServer.BlockInfo.blockHash)
  return blockhash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BlockInfo::release_blockhash() {
  // @@protoc_insertion_point(field_release:NameServer.BlockInfo.blockHash)
  
  return blockhash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BlockInfo::set_allocated_blockhash(::std::string* blockhash) {
  if (blockhash != NULL) {
    
  } else {
    
  }
  blockhash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), blockhash);
  // @@protoc_insertion_point(field_set_allocated:NameServer.BlockInfo.blockHash)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace NameServer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_NameServer_2eproto
