// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: multiple_rpc.proto

#include "multiple_rpc.pb.h"
#include "multiple_rpc.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace multiple_rpc {

static const char* InfoService_method_names[] = {
  "/multiple_rpc.InfoService/GetServerInfo",
};

std::unique_ptr< InfoService::Stub> InfoService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InfoService::Stub> stub(new InfoService::Stub(channel));
  return stub;
}

InfoService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetServerInfo_(InfoService_method_names[0], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::multiple_rpc::Address>* InfoService::Stub::GetServerInfoRaw(::grpc::ClientContext* context, const ::multiple_rpc::Address& request) {
  return ::grpc::internal::ClientReaderFactory< ::multiple_rpc::Address>::Create(channel_.get(), rpcmethod_GetServerInfo_, context, request);
}

::grpc::ClientAsyncReader< ::multiple_rpc::Address>* InfoService::Stub::AsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::multiple_rpc::Address& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::multiple_rpc::Address>::Create(channel_.get(), cq, rpcmethod_GetServerInfo_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::multiple_rpc::Address>* InfoService::Stub::PrepareAsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::multiple_rpc::Address& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::multiple_rpc::Address>::Create(channel_.get(), cq, rpcmethod_GetServerInfo_, context, request, false, nullptr);
}

InfoService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InfoService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< InfoService::Service, ::multiple_rpc::Address, ::multiple_rpc::Address>(
          std::mem_fn(&InfoService::Service::GetServerInfo), this)));
}

InfoService::Service::~Service() {
}

::grpc::Status InfoService::Service::GetServerInfo(::grpc::ServerContext* context, const ::multiple_rpc::Address* request, ::grpc::ServerWriter< ::multiple_rpc::Address>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace multiple_rpc

