//
// Created by JamesBrown on 2018/12/26.
//

#ifndef DISTRIBUTEDSYSTEMPROJECTS_DATASERVER_H
#define DISTRIBUTEDSYSTEMPROJECTS_DATASERVER_H


class DataServer {

};


#endif //DISTRIBUTEDSYSTEMPROJECTS_DATASERVER_H
