//
// Created by JamesBrown on 2018/12/26.
//

#ifndef DISTRIBUTEDSYSTEMPROJECTS_NAMESERVER_H
#define DISTRIBUTEDSYSTEMPROJECTS_NAMESERVER_H


class NameServer {

};


#endif //DISTRIBUTEDSYSTEMPROJECTS_NAMESERVER_H
